name: Unitary_Test_Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies for Linux
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libx11-dev libssl-dev pkg-config waylandpp-dev

    - name: Add target for web assembly build
      run: rustup target add wasm32-unknown-unknown

    - name: Install cargo-make
      run: cargo install cargo-make

    - name: Build - (Without winip)
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
