name: Unitary_Test_Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies for Linux
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev

    - name: Build
      run: cargo build --features testing --verbose

    - name: Run tests
      run: cargo test --features testing --verbose
